name: My sample learning workflows 
on:
  push:
    branches: [ wrkflows]
    

jobs:
  Build:
    name: Build JOB
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2 

      - name: List the contents
        run: |
          echo "The presnt directory is $(pwd)"
          echo "The contents of this repo are \n $(ls)"
