name: My sample learning workflows 
on:
  push:
    branches: [ wrkflows]
    

jobs:
  # sonarqube:
  #     name: SonarQube
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v4
  #         with:
  #           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis


  #       - name: SonarQube Scan
  #         uses: SonarSource/sonarqube-scan-action@v5
  #         env:
  #           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build:
    name: Build JOB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    permissions:
      contents: read

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2 

      - name: List the contents
        run: |
          echo "The presnt directory is $(pwd)"
          echo -e "The contents of this repo are \n $(ls)"
          echo "########## github details #######"
          echo "repo ${{ github.repository}}"
          echo "action ${{ github.action }}"
          echo "ref ${{ github.ref}}"
          echo "ref_name ${{ github.ref_name}}"
          echo "ref_protected ${{ github.ref_protected}}"
          echo "ref_type ${{ github.ref_type}}"
          echo "repository_owner ${{ github.repository_owner}}"
          echo "repositoryUrl ${{ github.repositoryUrl}}"
          echo "job ${{ github.job}}"
          echo "workflow ${{ github.workflow}}"
          echo "runner os : $RUNNER_OS"
      
      - name: testing 
        if: github.ref_name == 'wrkflows'  
        run: |
          echo "The branch is workflows"
          

